config/routes.rb
TicTacToe::Application.routes.draw do
  resources :users
  resources :games do 
    resources :moves
  end
  resources :sessions
  get '/logout', to: 'sessions#destroy'

 root :to => 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :player1_id, :player2_id, :winner, :player1, :player2

  belongs_to :player1, :class_name => 'User'
  belongs_to :player2, :class_name => 'User'
  belongs_to :winner, :class_name => 'User'
  has_many :moves

  scope :find_user, -> (user) {where('player1_id = :user_id OR player2_id = :user_id', {user_id: user.id})}


  def build_board
    @board = [nil, nil, nil, nil, nil, nil, nil, nil, nil]

    self.moves.each do |move|
      if move.player_id == self.player1.id
        @board[move.move] = 'X'
      else 
        @board[move.move] = 'O'
      end
    end
    @board
  end


  def game_winner
    @board
    @lines = [
      [ 0, 1, 2], 
      [ 3, 4, 5], 
      [ 6, 7, 8], 
      [ 0, 3, 6], 
      [ 1, 4, 7], 
      [ 2, 5, 8], 
      [ 0, 4, 8], 
      [ 6, 4, 2]]

    @lines.any? do |winning_line|
      result1 = winning_line[0]
      result2 = winning_line[1]
      result3 = winning_line[2]

      if @board[result1] == 'X' && @board[result1] == @board[result2] && @board[result1] == @board[result3]
        @win = true
        self.winner =  player1
      elsif @board[result1] == 'O' && @board[result1] == @board[result2] && @board[result1] == @board[result3]
        @win  = true
        self.winner = player2
      end
    end
  end

  def draw
    if (@win == false || @win.nil?) && (@board.include?(nil) != true)
      @draw = true
      "It's a draw!"
    end
  end

  def last_player
    if self.moves != []
      self.moves.last.player_id
    end
  end

  def computer_or_not
    if (self.player2_id == 1)
      self.computer_makes_move
    end
  end

  def game_over?
    (@win == true ) ||  (@draw == true)
  end

  def computer_makes_move
    if (self.player1_id == self.last_player)
      index = [0, 1, 2, 3, 4, 5, 6, 7, 8]
      number = index.sample
      @board[number]
      if (@board[number] == nil)
        Move.create(player_id: 1, game_id: self.id, move: number)
      end
    end
  end
  
end

app/controllers/games_controller.rb
  class GamesController < ApplicationController
    # GET /users
    # GET /users.json
    def index
      @games = Game.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @games }
      end
    end

    # GET /users/1
    # GET /users/1.json
    def show
      @game = Game.find(params[:id])

      # my own methods
      @board = @game.build_board
      @game_winner = @game.game_winner
      @last_player = @game.last_player
      @game.computer_or_not
      @game.game_over?
      
      @result = @game.draw
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @game }
      end
    end

    # GET /users/new
    # GET /users/new.json
    def new
      @game = Game.new
      # respond_to do |format|
      #   format.html # new.html.erb
      #   format.json { render json: @game }
      # end
    end

    # GET /users/1/edit
    def edit
      @game = Game.find(params[:id])
      
    end

    # POST /users
    # POST /users.json
    def create
      @game = Game.new(params[:game])
      @game.player1 = current_user

      respond_to do |format|
        if @game.save
          format.html { redirect_to @game, notice: 'Game was successfully created.' }
          format.json { render json: @game, status: :created, location: @game }
        else
          format.html { render action: "new" }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end


    # PUT /users/1
    # PUT /users/1.json
    def update
      @game = Game.find(params[:id])

      respond_to do |format|
        if @game.update_attributes(params[:game])
          format.html { redirect_to @game, notice: 'Game was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @game = Game.find(params[:id])
      @game.destroy

      respond_to do |format|
        format.html { redirect_to games_url }
        format.json { head :no_content }
      end
    end
  end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@game.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <h2> Pick your opponent! </h2>
  <%= f.collection_select( :player2_id , User.all.collect, :id, :username, :prompt => true) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/index.html.erb
<div class = 'middle'>

    <h2>Listing Games</h2>

    <% @games.each do |game| %>
        <td><%= link_to 'Show', game %></td>
        <td><%= game.player1.username %></td>
        <% if (game.player2 != nil) %>
            <td><%= game.player2.username %></td>
        <% end %>
        <td><%= game.created_at %></td>
        <% if (game.winner != nil) %>
            <td><%= @game_winner %></td>
        <% end %>
        <br>
    <% end %>

</div>

app/views/games/new.html.erb
<div class = 'middle'>

  <%= render 'form' %>

</div>

app/views/games/show.html.erb
<div class = 'game_players'>
  <p><%= image_tag('super.png', class: 'superhero')%><br>Player 1: <%= @game.player1.username %></p>
  <% if (@game.player2 != nil) %>
    <p><%= image_tag('bat.png' , class: 'superhero')%><br>Player 2: <%= @game.player2.username %></p>
  <% end %>
</div>


<div class = 'result'>
  <% if (@game.winner != nil) %>
    <h3><%= @game.winner.username %> wins!!!!</h3>
  <% end %>

  <% if (@result != nil) %>
    <h3><%= @result %></h3>
  <% end %>
</div>

<% if (@game.game_over? == false) %>
  <% if current_user.id == @last_player %> 
  <meta http-equiv="refresh" content="1">
  <% end %>
<% end %>

<div class = 'board'>
  <% @board.each_with_index do |move, square_id| %>
    <% if move == 'X' %>
      <%= image_tag('superman.png', class: "letter") %>
    <% elsif move == 'O' %>
      <%= image_tag('batman.png', class: "letter") %>
    <% else %> 
      <% if (@game.game_over? == false) %> 
        <% if current_user.id != @last_player %>
          <%= link_to new_game_move_path(@game, move: square_id) do %>
            <div class = 'letter unpicked'></div>
          <% end %>
        <% else %>
          <div class = 'letter unpicked'></div>
        <% end %>
      <% else %>
        <div class = 'letter'></div>
      <% end %>
    <% end %>
  <% end %>
</div>