config/routes.rb
TicTacToe::Application.routes.draw do
  resources :users
  resources :games do 
    resources :moves
  end
  resources :sessions
  get '/logout', to: 'sessions#destroy'

 root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToe</title>
  <link href='https://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Walter+Turncoat' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Patrick+Hand+SC' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <h1>TIC-TAC-Superhero</h1>
  </header>
  <div class = 'nav_line'></div>
  <nav>
    <% if current_user == nil %>
      <%= link_to('Register', new_user_path)%> 
      <%= link_to('Log In', new_session_path)%> 
    <% end %>
    <%= link_to('Players', users_path)%> 
    <% if current_user != nil %>
      <%= link_to('Profile', current_user)%> 
      <%= link_to('Play', new_game_path)%> 
      <%= link_to('Log Out', logout_path) %>
      <%= link_to('Games', games_path)%>
    <% end %>
  </nav>
  <div class = 'main'>
    <div class= 'flash_message'>
      <% if current_user %>
        <p>You're currently logged in as <%= current_user.username %></p>
      <% end %>

      <%= yield %>
    </div>
  </div>
</body>
</html>